import { Vector } from '../assets/vector/vector.icon';

export const AppImages = {
  LOGO: require('../assets/images/aaspass_logo.png'),
  LOGO_2: require('../assets/images/aaspass_logo.png'),
  BG_IMAGE: require('../assets/images/bg-image.png'),
  PROFILE: require('../assets/images/profile.jpeg'),
  CLEAN: require('../assets/images/clean.jpg'),
  CLEAN2: require('../assets/images/clean2.jpg'),
  CLEAN3: require('../assets/images/clean3.jpg'),
  CLEAN4: require('../assets/images/clean4.jpeg'),
  background: require('../assets/images/background.jpg'),
  background1: require('../assets/images/background1.png'),
  cloth: require('../assets/images/cloth.png'),
  grocery: require('../assets/images/grocery.png'),
  landing1: require('../assets/images/landing1.png'),
  landing2: require('../assets/images/landing2.png'),
  landing3: require('../assets/images/landing3.png'),
  splash: require('../assets/images/Splash.png'),
  gift: require('../assets/images/giftbox.png'),
  Vector1: require('../assets/images/vector.png'),
  fencing: require('../assets/images/fencing.png'),
  girl: require('../assets/images/girl.png'),
  shop: require('../assets/images/shop.png'),
  dicount: require('../assets/images/discount.png'),
  shirt: require('../assets/images/shirt.png'),
  blackT: require('../assets/images/blackT.png'),
  suit: require('../assets/images/suit.png'),
  jeans: require('../assets/images/jeans.png'),
  raymond: require('../assets/images/raymond.png'),
  levis: require('../assets/images/levis.png'),
  gucci: require('../assets/images/gucci.png'),
  peter: require('../assets/images/peter.png'),
  filter: require('../assets/images/filter.png'),
  all: require('../assets/images/all.png'),
  Fshirt: require('../assets/images/Fshirt.png'),
  Fpant: require('../assets/images/Fpant.png'),
  skirt: require('../assets/images/skirt.png'),
  setting: require('../assets/images/setting.png'),
  avatar: require('../assets/images/avatar.jpg'),
  wishlist: require('../assets/images/wishlist.png'),
  remove: require('../assets/images/remove.png'),
  cod: require('../assets/images/cod.png'),
  edit: require('../assets/images/edit.png'),
  location: require('../assets/images/location.png'),
  camera: require('../assets/images/camera.png'),
  mic: require('../assets/images/mic.png'),
  // Figma design se export ki gayi assets
  headerBg: require('../assets/images/figma_header_bg.jpg'),
  headerLights: require('../assets/images/figma_lights.png'),
  headerFence: require('../assets/images/figma_fence.png'),
  promo1: require('../assets/images/promo1.png'),
  promo2: require('../assets/images/promo2.png'),
  sportswear: require('../assets/images/sportswear.png'),
  newLogo: require('../assets/images/newLogo.jpeg'),
  card: require('../assets/images/Card.png'),
  card2: require('../assets/images/Card2.png'),
};
